defaults:
  - default_dataset.yaml
  - default_model.yaml
  - _self_

exp_name: exp001
img_size: 256
num_workers: 8
seed_value: 42
accum_steps: 4    # Gradient accumulation, use if OOM occurs
patch_size: 14
val_epoch_freq: 5
max_img_per_gpu: 1
max_epochs: 10

limit_train_batches: 800
limit_val_batches: 400

data:
  train:
    _target_: data.dynamic_dataloader.DynamicTorchDataset
    num_workers: ${num_workers}
    max_img_per_gpu: ${max_img_per_gpu}
    common_config:
      img_size: ${img_size}
      patch_size: ${patch_size}
      debug: False
      repeat_batch: False
    dataset:
      _target_: data.composed_dataset.ComposedDataset
      dataset_configs:
        - _target_: data.datasets.co3d.Co3dDataset
          split: train
          CO3D_DIR: /content/co3d_data
          CO3D_ANNOTATION_DIR: /content/co3d_annotations
  val:
    _target_: data.dynamic_dataloader.DynamicTorchDataset
    num_workers: ${num_workers}
    max_img_per_gpu: ${max_img_per_gpu}
    common_config:
      img_size: ${img_size}
      patch_size: ${patch_size}
      debug: False
    dataset:
      _target_: data.composed_dataset.ComposedDataset
      dataset_configs:
        - _target_: data.datasets.co3d.Co3dDataset
          split: test
          CO3D_DIR: /content/co3d_data
          CO3D_ANNOTATION_DIR: /content/co3d_annotations

logging:
  log_dir: logs
  log_visuals: False
  log_freq: 1
  log_level_primary: DEBUG
  log_level_secondary: WARNING
  all_ranks: False
  tensorboard_writer:
    _target_: train_utils.tb_writer.TensorBoardLogger
    path: ${logging.log_dir}/tensorboard
  scalar_keys_to_log:
    train:
      keys_to_log:
        - loss_objective
        - loss_camera
        - loss_T
        - loss_R
        - loss_FL
        - loss_conf_depth
        - loss_reg_depth
        - loss_grad_depth
    val:
      keys_to_log:
        - loss_objective
        - loss_camera
        - loss_T
        - loss_R
        - loss_FL
        - loss_conf_depth
        - loss_reg_depth
        - loss_grad_depth

checkpoint:
  save_dir: logs/${exp_name}/ckpts
  save_freq: 5
  resume_checkpoint_path: null

cuda:
  cudnn_deterministic: False
  cudnn_benchmark: True
  allow_tf32: True

distributed:
  backend: "nccl"
  timeout_mins: 30
  find_unused_parameters: False   # <-- added to fix DDP error

# ---------------------------
# Optimizer, Scheduler, Gradient Clip
# ---------------------------
optim_conf:
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.0001
    weight_decay: 0.00001

  options: null   # no scheduler for now

  amp:
    enabled: True
    amp_dtype: float16

  gradient_clip:
    _target_: train_utils.optimizer.GradientClipNorm
    max_norm: 1.0